# Generated by Django 4.2.4 on 2023-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_newarticle_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarticle',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
