# Generated by Django 4.2.4 on 2023-10-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newarticle_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newarticle',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AlterField(
            model_name='newarticle',
            name='slug',
            field=models.SlugField(verbose_name=models.CharField(max_length=100)),
        ),
    ]
