# Generated by Django 4.2.4 on 2023-10-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_newarticle_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.newarticle'),
        ),
    ]
