# Generated by Django 4.2.4 on 2023-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarticle',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
