# Generated by Django 4.2.4 on 2023-10-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_newarticle_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarticle',
            name='thumbnail',
        ),
    ]
