# Generated by Django 4.2.4 on 2023-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_newarticle_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarticle',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='newarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/005/545/335/small/user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
