# Generated by Django 4.2.4 on 2023-10-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_newarticle_images_newarticle_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarticle',
            name='images',
        ),
    ]
