# Generated by Django 4.2.4 on 2023-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogposts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
