# Generated by Django 4.2.4 on 2023-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_popularposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='popularService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduce', models.TextField(max_length=2000)),
                ('images', models.ImageField(default='https://static.vecteezy.com/system/resources/thumbnails/005/545/335/small/user-sign-icon-person-symbol-human-avatar-isolated-on-white-backogrund-vector.jpg', upload_to='images/%y/%m/%d')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
    ]
