# Generated by Django 4.2.4 on 2023-09-23 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_popularservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='popularPosts',
            new_name='popularPost',
        ),
    ]
